#!/bin/bash
in=$1
out=$2

if [   -e $out ] ; then echo \! $out ; exit 1 ; fi
if [ ! -e $in  ] ; then echo \? $in  ; exit 1 ; fi

sed '/./{H;d;};x;s/\n/={NL}=/g' $in | sed -e 's/^={NL}=//' -e '1!G;h;$!d' | sed G  | sed 's/={NL}=/\'$'\n/g' > $out

