#!/bin/bash

if [   -e $1 ] ; then echo \! $1 ; exit 1; fi
if [ ! -e $2 ] ; then echo \? $2 ; exit 1; fi
if [ ! -e $3 ] ; then echo \? $3 ; exit 1; fi

if ! grep -q PATH $2 ; then echo \? $2 ; exit 1; fi
if ! grep -q PATH $3 ; then echo \? $3 ; exit 1; fi

sed -n '/PATH/,$p' $2 >> $1
sed -n '/PATH/,$p' $3 >> $1

